### ISSUE TITLE
带头结点的单链表文件中，指定节点前插操作有点问题

### ISSUE THREAD

**Issue by NetworkLatency** [markyin0707/DataStructure-Study#1]
//指定节点前插操作（有无头节点都可）,时间复杂度 O(1)
bool InsertPriorNode(LNode *p,int e){
    if(p==NULL)
        return false;
    LNode *s=(LNode*)malloc(sizeof(LNode));
    if(s==NULL)
        return false;
    s->next=p->next;
    s->next=s;    **//这里是不是应该写成p->next=s;**
    s->data=p->data;
    p->data=e;
    return true;
}

**Comment by eglhub** [comment]
感谢提醒，已经修正错误👍
